services:
  database:
    image: postgres:18-alpine
    container_name: spring_questoes_api
    environment:
      POSTGRES_DB: spring_questoes_api
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
